#!/usr/bin/env bash

function main {
  local shome="${_vagrant_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  local nm_provider="$VAGRANT_DEFAULT_PROVIDER"
  local pth_box=

  if [[ -f "$nm_provider" ]]; then
    pth_box="$nm_provider"
    nm_provider=
  else
    pth_box="$(set +f; ls -trd "${BASEBOX_CACHE}/box/$nm_provider"/*${1:+-$1*}.box | tail -1)"
  fi

  exec vagrant box add --name ${BASEBOX_NAME}${2:+-$2} "${pth_box}"
}

source sub "$0" "$@"

