#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_guest="$1"; shift
  local cfg_ssh="$shome/.vagrant-${nm_guest}-ssh-config"

  parity ssh config "$nm_guest"
  exec rsync -e "$(printf 'ssh -F %q' "$cfg_ssh")" "$@"
}

main "$@"
