#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_guest="$1"; shift
  source "$shome/exec/vagrant_common"

  if [[ ! -e "$cfg_ssh" ]]; then
    vagrant ssh-config "$nm_guest" > "$cfg_ssh.tmp"
    mv -f "$cfg_ssh.tmp" "$cfg_ssh"
  fi
  cat "$cfg_ssh"
}

main "$@"
