#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_guest="$1"; shift
  source "$shome/exec/vagrant_common"

  parity ssh_config "$nm_guest" > /dev/null
  scp -F "$cfg_ssh" "$@"
}

main "$@"
