#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_guest="$1"; shift
  source "$shome/exec/vagrant_common"

  rm -f "$cfg_ssh"
  if vagrant reload "$nm_guest" "$@"; then
    parity ssh_config "$nm_guest"
  fi

}

main "$@"
