#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_guest="$1"; shift
  local cfg_ssh="$shome/.vagrant-${nm_guest}-ssh-config"

  parity ssh_config "$nm_guest" > /dev/null
  exec ssh -F "$cfg_ssh" -o IdentitiesOnly=no "$nm_guest" "$@"
}

source sub "$BASH_SOURCE" "$@"
