#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  export VAGRANT_DEFAULT_PROVIDER="aws"

  if [[ -d .terraform ]]; then
    exec fogg env vagrant "$@"
  else
    exec vagrant "$@"
  fi
}

source sub "$0" "$@"
