#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  export VAGRANT_DEFAULT_PROVIDER="virtualbox"

  exec vagrant "$@"
}

source sub "$0" "$@"
