#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_vagrant='1.8.0'

  case "$(uname -s)" in
    Darwin)
      app compile dmg \
        "https://releases.hashicorp.com/vagrant/${ver_vagrant}/vagrant_${ver_vagrant}.dmg" \
        'Vagrant' 'Vagrant.pkg'
      ;;
    Linux)
      local url_vagrant="https://releases.hashicorp.com/vagrant/${ver_vagrant}/vagrant_${ver_vagrant}_x86_64.deb"
      curl -sS -L -o "vagrant_${ver_vagrant}_x86_64.deb" "$url_vagrant"
      sudo dpkg -i "vagrant_${ver_vagrant}_x86_64.deb"
      rm -f "vagrant_${ver_vagrant}_x86_64.deb"
      ;;
  esac
}

bootstrap
