#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      block compile dmg \
        "https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.dmg" \
        'Vagrant' 'Vagrant.pkg'
      ;;
    Linux)
      local url_vagrant="https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.deb"
      local fnm_vagrant="$(basename "$url_vagrant")"
      cache curl "$fnm_vagrant" "$url_vagrant"
      sudo dpkg -i "${BASEBOX_CACHE}/curl/$fnm_vagrant"
      ;;
  esac
}

bootstrap
