#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$(block version | jq -r '.terraform')" != "$VAGRANT_VERSION" ]]; then
    return 1
  fi

  return 0
}

source sub "$0" "$@"
