#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$($shome/script/version | jq -r '.vagrant')" != "$VAGRANT_VERSION" ]]; then
    return 1
  fi

  if ! type -P bsdtar >/dev/null; then
    return 1
  fi

  return 0
}

source sub "$0" "$@"
