#!/usr/bin/env bash

function _vagrant_profile {
  local shome="${_vagrant_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"

  VAGRANT_VERSION='1.9.5'

  export VAGRANT_I_KNOW_WHAT_IM_DOING_PLEASE_BE_QUIET=1
  export VAGRANT_BOX_UPDATE_CHECK_DISABLE=1
  export VAGRANT_CHECKPOINT_DISABLE=1
}

_vagrant_profile
