#!/usr/bin/env bash

function profile {
  local shome="${_vagrant_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"
  #export VAGRANT_HOME="${VAGRANT_HOME:-shome/.vagrant.d}"
}

profile
