#!/usr/bin/env bash

function main {
  local shome="${_vagrant_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  if [[ -x "$(which /usr/bin/vagrant /usr/local/bin/vagrant 2>/dev/null || true)" ]]; then
    return 1
  else
    return 0
  fi
}

source sub "$0" "$@"
