#!/usr/bin/env bash

function vagrant_update {
  local shome="${_vagrant_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  (set +f; rm -vf "$shome"/.vagrant*ssh-config)
}

vagrant_update
