#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_vagrant="$(vagrant --version 2>/dev/null | awk '{print $2}' || true)"
  jq -n -s --arg vagrant "$ver_vagrant" '{vagrant: $vagrant}'
}

version "$@"
